[package]
name = "qiniu-download"
version = "0.0.9"
description = "Qiniu Resource (Cloud) Download SDK for Rust."
authors = ["Bachue Zhou <bachue.shu@gmail.com>"]
documentation = "http://developer.qiniu.com"
readme = "README.md"
edition = "2018"
keywords = ["qiniu", "storage", "sdk", "cloud"]
license = "MIT"

[dependencies]
base64 = "0.10.1"
sha-1 = "0.8.1"
url = "2.1.0"
hmac = "0.7.1"
crypto-mac = "0.7.0"
reqwest = { version = "0.10.8", features = ["blocking"] }
once_cell = "1.4.1"
positioned-io = "0.2.2"
rand = "0.7.3"
multipart = { version = "0.17.1", package = "qiniu-multipart" }
rayon = "1.4.1"
sema = "0.1.4"

[dev-dependencies]
futures = "0.3.5"
warp = "0.2.5"
tokio = { version = "0.2.22", features = ["rt-core", "blocking", "macros"] }
structopt = "0.3.18"
anyhow = "1.0.32"
